travis:
  secure:
    BINSTAR_TOKEN: s1kIyPHsioPY+adNlC1O6UyFsHTuPz3XzGa+ZsOOZBLpShZKDyFu4MYAVXndJGt+wYTUA30es8k6r+Cdn6QT5fLVaSsgEgj8MwjYFyD6HABjGcssssiQ5UDsoFgZqs3O8qa60ZJaEWXK0JaVxOc3sevbtvbQLo9LgmXPHxJCPyIVuGd8FkirlyiBIwFlQtI9ytn/7T+hOsSjGI+NIAWkX70NG67qeDUrzrLgKMDqXv6Y2SGNwieutWtocuClNW5JPugeU6mlJyrwRcPqQKQR/fCJ9vTn26x4PxeItpr4pQPNOO9v7gUrYmsD8ZJNGDBFaFGAyPGEd+D5Cf81S0B2BgKB43vuJAbIWUIizs57fqKAYjA4wiF8M4ge7IsZLUF1IKpaia/VSiQzYEgO4YjCy8FfyF6y6R8CdptHTxaeTjpBl7lfVIHGtueCPSaRSOuc4fXO+PSfWOolIQrefeuuBlQeMOykVGk3KWkuaw5kp0MXIT/stFf+B2ydg1uePJuJuesRi3rNRknaxxoXVyDbNlvMbXJ8IMtXXmFdr94ZCsdE1V/9BYYuygyoFAa3nfyknvoVpGjUM+wOO4G5GknYNYNyJMHO1KR3nqtX1hKbLSY5igu2NDPL6SoVqiiRRCyoXINIixbuzjnupWqO3NLoR8cwAaJMlxf03qm7ZcOyx6Q=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
