travis:
  secure:
    BINSTAR_TOKEN: CMXQ2b4RUysAZhyAaY79B+ICwsLSDkbbhjqlz/QwvULoInnkfvBKQSqzozM/jS2Og7VTT90uMh+2nqw1K0wMe8YdEMNnucoewRwctpNB17WeWkqoY2y4Gb7PVZ7tlxgJKNmP0WEGMOnJNXV1i2QQ1AYOF2raMZbrA/SAv2oPZTEsnVTPFU4JIXL8cDy/cU1tASNoIzuEQH69rNLSTgiPJkwf9hrjTT5+FYNQhhDih0BKuZFl43bZ2hmN1x9DGfXACthXe+CLJfpXoeCO78mRRir7iXFtpGgCiDBRqNSglL90LqrAyLcpEhOMxAISNzKKrBB0h1UELEVyedlSKakmAQtPPg2iCs2sA+LwsearGxQw/Fa8PRNSmmWFnFq5P7ra6No2Uf4iHJuC/dcNIqAKGNq6XY9WVHwALaEd5bRheAT9UphaxjvolvLOhfrbdbOvOu2vKLvzR47qaawmmeN8loXq8uZnuDgKmbEXVJP0IkwZQO4QcuSsHxnII2vh5vNtjC8uEC9LojVu1TIFKaEWEPpn0OaKI2yqz1S6ROyK1xjXqkg/gCvvzAMgpcyqK55CM42JReg8ZPrNv82k02/MfYcXAxCv9To0FSzVYQhJkQ4nj84RyeI5yC5FwwFton2B8ZCp/a7ce0DC09UQIlP/4u28p3N62dytqs8wVpc2RPU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
