travis:
  secure:
    BINSTAR_TOKEN: wN7Iq8yCJ9ejW8QWXNlayOx7GorGzSYl/xDB+C0ccJ+qxTt3XtW8mTlv8xMsIPoZxiy5dS3wOhEPxwWH18NnQzpvhpT63P2M4lBihEvYwsyfl8iMJDeUb+2IizG1mKQk4FwDZOQPtlRWsrrhQtR2/qggimtuZwo2lyB7zZbExsQEufNT7L9YXsIXA9MZLeBoAlpSaGbEDn5vFIeKmzfpzN5i7UpThc++z2V6TTcQ0nFLaNj49fV960qije4YFy/TcUWz80hZsNRLvW9m/oovOiojPRTDniJCO0Iq7+c5DKMS4+9bD7C+K4lt++8orhwwHAwPog15628+1PtdqA+0Ra47oz/QVZSXlThA4Hx8RxOjkvbzySRvh+Y7ddLxmJXxzGXrsR1ZHwpRPVt+Uhd75mRJfiuN5ksvy6rr5tTUKE4t7nlGJQ+QUuIjp4n6Q/5wF6KZyNy6UfdJXBuSbJPHDdmwzP2ulexqFN+TDtdLGtJK9L2rt38w6mXZ06QpP/Q97+gD8pi0bOwzv9Q9Q1ZV/wEph2lH0bO3Twga1PoupRleEgo9MbuqdJ2oTwLxizbtRqV9nFqjzgMYOc0zfJTcDON8yO80MqJIWWyxm1ymGnYRpykoZXH1V6o1z1oQnexKw55pfpFhqotkkYDrHuM7XrrVVfISpb/HI09qn2KC8LA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
